# Generated by Django 6.0.5 on 2026-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=50)),
                ('condition_id', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('pathogen', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
