# Generated by Django 6.0.5 on 2026-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(choices=[('tomato', 'Tomato'), ('maize', 'Maize'), ('pineapple', 'Pineapple')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
