# Generated by Django 6.0.6 on 2026-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
    ]
